In [1]:
#importing modules and preparing dataset
import numpy as np
import pickle
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [2]:
from sklearn.preprocessing import LabelEncoder

In [3]:
#Encoding the labels
le = LabelEncoder()
weather_en = le.fit_transform(weather)
temp_en = le.fit_transform(temp)
label = le.fit_transform(play)

In [4]:
weather_en

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1], dtype=int64)

In [5]:
temp_en

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2], dtype=int64)

In [6]:
label

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [7]:
features=list(zip(weather_en,temp_en))
print(features)

[(2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2)]


In [8]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(features,label)

GaussianNB(priors=None, var_smoothing=1e-09)

In [9]:
filename = 'gameplay_model.sav'
pickle.dump(model,open(filename,'wb'))